### ISSUE TITLE
Hovering over links should show URL in status bar

### ISSUE THREAD

**Issue by ajgraves** [vladimiry/email-securely-app#100]
I usually validate any URL before I click on a link, regardless of the source of an email. That said, I've noticed that when hovering over a link, I get neither a tooltip (which should be the minimum IMO) or a status bar at the bottom which displays the URL for the link.

**Comment by vladimiry** [comment]
Actually, the app does highlight the links on hover event, but only in database mode at the moment.

![link-hover](https://user-images.githubusercontent.com/1560781/51889529-ebdc3300-23aa-11e9-9c35-4d47525497fc.gif)

**Comment by vladimiry** [comment]
Thanks for the feedback. Here is the [pre v 2.2.1](https://www.dropbox.com/sh/y413x6c06tt7kbf/AAAtO3tsjsnH40EHVMHpVmy_a?dl=0&lst=) build which includes the unified hovered links highlighting, can you confirm it solves the issue?

![hover4-optimized](https://user-images.githubusercontent.com/1560781/51900518-944bc080-23c6-11e9-83b0-af6c43883eac.gif)

**Comment by ajgraves** [comment]
One thing, as a suggestion (and this is entirely a matter of aesthetics) perhaps anything under the protocol webclientX (where X is a number) could be suppressed (these appear to be all "internal" links to different pages/folders, etc)

**Comment by vladimiry** [comment]
I tend to keep showing the full urs for the sake of explicitness.

`webclientX://` (where X is a number) is a custom in-app http protocol which indicates that a built-in/prepackaged web client is being used. See https://github.com/vladimiry/email-securely-app/issues/80 and https://github.com/vladimiry/email-securely-app/issues/79 for details. If you choose in the account settings for example https://beta.protonmail.com domain, then such urls will start with normal `https://` protocol.

So I might want to reconsider after dropping https://beta.protonmail.com/ entry point support, which is the only remaining supported `online` web client.

**Comment by ajgraves** [comment]
That's fair, that's why I only "suggested". Thanks again!

**Comment by vladimiry** [comment]
Ok, let's close once released.

**Comment by vladimiry** [comment]
Released with [v2.3.0](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.0).
