### ISSUE TITLE
yarn run electron-builder:dir fails

### ISSUE THREAD

**Issue by odiferousmint** [vladimiry/email-securely-app#101]
Ideas?

`yarn run electron-builder:dir` fails with:
```
 Error: Application entry file "app/electron-main.js" in the "/home/odiferousmint/email-securely-app/dist/linux-unpacked/resources/app.asar" does not exist.
```

**Comment by vladimiry** [comment]
`yarn run electron-builder:dir` is the final command but the app needs to be built first, see readme for details.

I need to see the complete sequence of commands you executed.

**Comment by vladimiry** [comment]
Closing as no additional information has been provided.
