### ISSUE TITLE
Allow database view mode select email in online mode

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/email-securely-app#102]
So you found an email in the offline database using full-text search and you want open the same found email in online mode to do something with it (like replying, removing, etc).

**Comment by vladimiry** [comment]
The feature has been implemented and will  be released soon.

![ezgif com-optimize](https://user-images.githubusercontent.com/1560781/52174073-badf7200-279f-11e9-95db-3b0cdbed5352.gif)

**Comment by vladimiry** [comment]
Released with [v2.3.0](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.0).

**Comment by MasterGroosha** [comment]
Doesn't work for me. Always shows Protonmail's popup "Message doesn't exist"

**Comment by vladimiry** [comment]
I need to be able to reproduce the problem in order to provide a reliable fix it. So any info that might help to detect a pattern is welcomed. Can you try for example jumping to emails in different folders, to recent/old emails, using another account, using free/paid account, etc.

**Comment by MasterGroosha** [comment]
@vladimiry tried Inbox, Sent, Trash and Starred on 2 different free accounts. Always shows "Message does not exist" error popup. Protonmail version 3.15.16.

**Comment by joshirio** [comment]
I can confirm this is not working for me. Tried on 3 accounts, with and without labels, different folders (archive, starred, sent).

**Comment by vladimiry** [comment]
Just tested v2.3.0 build on linux/mac/win platforms, still working.

- Did you also try clicking "view online" from the search result view?
- Does it work for Tutanota?

**Comment by vladimiry** [comment]
It's unlikely to be helpful but if you want to try it, I just uploaded [here](https://www.dropbox.com/sh/h3jedzue0kwgopr/AABb7VnDdDSUpbKaUBl1XC_Pa?dl=0&lst=) work-in-progress 2.3.1
 build.

**Comment by joshirio** [comment]
Hey I've found the bug. If you disable message grouping (settings->appearance) it doesn't work. Enabling grouping solves the issue. Looks like the local storage view automatically groups the emails, maybe because it's protonmail's default model.

So everyone who doesn't use grouping will face the error.

**Comment by vladimiry** [comment]
This is a very good find. I was not even aware of that protonmail has such feature as I'm not using it heavy, nor the tuatnota, but gmail :smile:

Going to look into the grouping thing and then make needed adjustments at the app side.

**Comment by vladimiry** [comment]
> Looks like the local storage view automatically groups the emails

The app groups the messages to conversations list y default, but you can make it show the emails as plain list, see this green toggle icon:

![peek](https://user-images.githubusercontent.com/1560781/52346314-6868b480-2a30-11e9-8b04-c6abf9f42a6a.gif)

**Comment by vladimiry** [comment]
Version with the fix included uploaded [here](https://www.dropbox.com/sh/h3jedzue0kwgopr/AABb7VnDdDSUpbKaUBl1XC_Pa?dl=0&lst=), can someone confirm issue is gone? I will publish a new release then.

**Comment by joshirio** [comment]
Yes, works fine :)

**Comment by vladimiry** [comment]
Fix has been released with [v2.3.1](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.1) build.
