### ISSUE TITLE
Protonmail: Update required: Please refresh the page to load the latest version of the application

### ISSUE THREAD

**Issue by Heziode** [vladimiry/email-securely-app#105]
Hi,

I get this error when it try to connect to my protonmail accounts: `Update required: Please refresh the page to load the latest version of the application`.

OS: Archlinux
App version: 2.2.0

**Comment by vladimiry** [comment]
v2.2.0 comes with 3.15.12 built-in protonmail's web client. Looks like protonmail's backend requires web client version to be updated and so they show a respective message.

So you have 2 options:
- Switch to the online web client in account's settings. https://beta.protonmail.com is the only remaining online web client's entry point. Not recommended option.
- Use the most recent app version which is [v2.3.1](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.1) at the moment. It comes with 3.15.16 built-in protonmail's web client.

**Comment by Heziode** [comment]
Indeed, the second solution works.
