### ISSUE TITLE
Master password setup showing failed to login

### ISSUE THREAD

**Issue by mojoman11** [vladimiry/email-securely-app#111]
Installed via the AUR, using dwm as my window manager.
As soon as i launched the app it asks me for a master password setup. I'm a bit confused whether 
1. I have to create a new password.
2. Use the same password as my already setup default keyring. I already use another client called [mailspring](https://github.com/Foundry376/Mailspring).

Either way I have tried both which constantly says "Failed to Login". Please advice.

Thank you for your hard work, looking forward to using it!

**Comment by vladimiry** [comment]
`settings.bin` file is encrypted using the master password the app asks you to enter in the fist start. This password is owned by `email-securely-app`, has nothing to do with `mailspring` or other apps.

> Either way I have tried both which constantly says "Failed to Login". Please advice.

Anything useful in the log file? If you think log lines might contain sensitive information consider sending it to the email specified [here](https://github.com/vladimiry/email-securely-app/blob/master/package.json#L5) in the `author` section.

**Comment by mojoman11** [comment]
I deleted the settings.bin file and setup everything again and it works!
Thanks again!
