### ISSUE TITLE
2FA Auto Login & Authy

### ISSUE THREAD

**Issue by trymeouteh** [vladimiry/email-securely-app#114]
Is it possible to use Authy and the apps automatic 2FA login with your ProtonMail account and your Tutanota account? If so I cannot figure it out since I need to either not use Authy or I have to enter my 2FA code every time I log in.

**Comment by vladimiry** [comment]
See screenshot here https://github.com/vladimiry/email-securely-app/issues/10

**Comment by trymeouteh** [comment]
Is it possible to use Authy and the email-security-app 2FA?

**Comment by vladimiry** [comment]
The app doesn't need Authy to automatically fill the 2FA token.
Supporting Authy or other similar third-party tools is not planned.

**Comment by trymeouteh** [comment]
I am confused. I have a ProtonMail account and a Tutanota account. I have both accounts with 2FA enabled using the Authy app. I also have two computers I want to use ElectronMail with.

To allow ElectronMail to login to my Tutanota account is easy since to add my Tutanota account to ElectronMail I just had to log into my account in my browsers. Go to Second Factor Authentication and add a new second factor authentication and set that up with my ElelectronMail. I did this on both computers and I still have Authy for 2FA with my Tutanota account and did not have to delete my Authy 2FA code.

ProtonMail however you are unable to add more than one method of 2FA. I have it setup in Authy but even when I disable 2FA and re-enable 2FA I am unable to pair it to Authy and my two computers at the same time. This is what I do not understand.

**Comment by vladimiry** [comment]
Authy generates the one-time tokens based on the secret seed same as ElectronMail does it. Then I guess Authy shares the secret seed between different devices. I think you can try to extract secret seed from Authy. Normally 2FA management programs allow doing that. Try looking up on the internet how to do that with Authy ([here](https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93) is something and [here](https://randomoracle.wordpress.com/2017/02/15/extracting-otp-seeds-from-authy/)).
