### ISSUE TITLE
Feature Request: Offline Mode

### ISSUE THREAD

**Issue by trymeouteh** [vladimiry/email-securely-app#115]
If you have no internet connection allow users to view all the email that has been received. Essentially every email that has been opened should be accessible on the computer but stored in a secure way using encryption. This way if you have no internet but need to read an old email your able to by launching the program and surfing your inbox.

**Comment by vladimiry** [comment]
This is already implemented since v2.0.0. Full-text search is also supported, including the offline mode.

I'd recommend reviewing the [release notes](https://github.com/vladimiry/email-securely-app/releases) of all the released published since v2.0.0.

**Comment by trymeouteh** [comment]
My bad, I havent updated the app in awhile.
