### ISSUE TITLE
using 'tabs' instead of a dropdown menu in the compact view

### ISSUE THREAD

**Issue by jeroen7s** [vladimiry/email-securely-app#36]
using tabs instead of the dropdown menu for the account switcher would improve usability in the compact view

**Comment by vladimiry** [comment]
Agreed, putting to todo list.

**Comment by vladimiry** [comment]
This is available with a new v1.2.0 release, which is on the way.

App now has 3 layout modes, `full`,  `tabs`, and `dropdown`, with even less code than it was before:

![toggling](https://user-images.githubusercontent.com/1560781/43053165-d2e46be0-8e33-11e8-8b93-07d22d5f1677.gif)

App activates `dropdown` mode automatically on the small screens. `Tabs` view mode is a multi-row fluid thing, you can there put as many accounts as you want.

As a bonus with the new version we also get the following improvements:
- In `full` mode accounts list column has no fixed width anymore, but fluid width. So there will be no line breaking anymore.
- `Options / menu` button is now always positioned in the top-left corner. So you will not be confused anymore with options button jumping across the screen in along with switching the view mode.

Thanks for highlighting a missing feature.

**Comment by vladimiry** [comment]
v1.2.0 got [published](https://github.com/vladimiry/email-securely-app/releases/tag/v1.2.0).

**Comment by jeroen7s** [comment]
awesome!
thanks a lot for making this app
without it i'm not sure I would be using PM and Tutanota anymore
