### ISSUE TITLE
macOS: system tray icon no longer shows message count only a red dot

### ISSUE THREAD

**Issue by joshirio** [vladimiry/email-securely-app#38]
Not sure which version caused the regression since I haven't been updating the app on a few macs for a couple of months.

The dock icon works fine, showing the unread message count, while the system icon shows only a red dot with a white artifact.

<img width="229" alt="tray" src="https://user-images.githubusercontent.com/12795018/43358378-dd67982e-9290-11e8-8030-a4d6de525bf6.png">

<img width="69" alt="dock" src="https://user-images.githubusercontent.com/12795018/43358381-e0d30426-9290-11e8-8eb7-6ebec392ee36.png">

This is just a minor issue but still wanted to report it.

Thanks.

**Comment by vladimiry** [comment]
It's because rendering of the red circle with a number on it moved from the web process to the backend process since I wanted backend gets only the unread value as a number, but not as a pre-rendered image (binary data). It's marked with [TODO](https://github.com/vladimiry/email-securely-app/blob/master/src/electron-main/api/endpoints-builders/tray-icon.ts#L16) and going to be handled.

v0.4.3 is the last version that does red circle rendering in the web process. But I'd recommend updating to v1.3.0 as it handles multiple accounts better than previous versions.

**Comment by vladimiry** [comment]
@joshirio can you try [this](https://www.dropbox.com/s/le5rx0hq253266k/email-securely-app-1.3.1-mac.dmg?dl=1) version?

**Comment by joshirio** [comment]
slightly better but the whole icon and the numbers are really blurred and hardly readable

How it looks:
<img width="1113" alt="2" src="https://user-images.githubusercontent.com/12795018/43367834-84918fde-9353-11e8-9ce1-b7ce8cea4754.png">

<img width="1110" alt="1b" src="https://user-images.githubusercontent.com/12795018/43367836-89f19c6c-9353-11e8-8766-538af325c2b7.png">

**Comment by vladimiry** [comment]
Pre-released [v1.3.1](https://github.com/vladimiry/email-securely-app/releases/tag/v1.3.1) should render a more sharpen tray icon on macOS, can you confirm it does?

**Comment by joshirio** [comment]
Looks good, thank you
![wire 2018-07-30 at 14 34 22](https://user-images.githubusercontent.com/12795018/43397682-fba50e72-9405-11e8-96b8-775acf50b684.png)

**Comment by vladimiry** [comment]
@joshirio would be great if you could you try [pre-3.2.1](https://www.dropbox.com/sh/ynlbt12stlo2kg7/AADgpmsBElrricd-lfrNe7CMa?dl=0&lst=) build on macOS. The build should render less burred tray icon on macOS. Here is the [related commit](https://github.com/vladimiry/ElectronMail/commit/8a1340d7c8c5c6dd968b3be19e4c9a7c72a4bddd).

**Comment by joshirio** [comment]
I don't have a HiDPI display on macOS to test it properly, but this is what I can say:
This is how the new icon with the counter looks:
![new](https://user-images.githubusercontent.com/12795018/56679681-f6664a00-66c5-11e9-8541-b849628f86c6.png)

Compare it with the old one, which clearly looks better:
![old](https://user-images.githubusercontent.com/12795018/56679683-f8300d80-66c5-11e9-9def-5f184cae6cd7.png)

Hope this helps.

**Comment by vladimiry** [comment]
Thanks for testing. The new build is supposed to have sharpened tray icon on macOS as there is no image downscaling anymore. At least in a virtual machine I run it looks better. The old icon rendering is unlikely to getting back.

**Comment by vladimiry** [comment]
The first screenshot looks similar to the attached here https://github.com/vladimiry/ElectronMail/issues/38#issuecomment-408684792 Without downscaling the app renders the red circle and number on it on 16x16 canvas which seems to be small for sharpened small parts rendering. I guess I could try rendering on 128x128 canvas like on Linux and then downscale using Lanczos3 algorithm.
