### ISSUE TITLE
Protonmail: No new email notification for email aliases (Premium)

### ISSUE THREAD

**Issue by joshirio** [vladimiry/email-securely-app#39]
Hi,

if one uses additional email aliases (protonmail premium feature) no desktop notification is shown, although the app recognizes the unread count correctly.

Note that the notification works with the free username@pm.me address but not with custom aliases.

**Comment by vladimiry** [comment]
- Does the unread red badge near to the account show the correct unread summary number (summary for the account, ie for all the aliases)?
- Do you get correct unread summary number rendered on the tray icon?

If the app notices that a number of unread messages became bigger than the previous value, then it shows a desktop notification, per account logic. Which means if unread badge near to the account got increased (app noticed a change), then desktop notification is supposed to be shown. This would be a bug if app notices a change and increases a red badge, but doesn't show a respective desktop notification. And would be an enhancement if app doesn't notice a change (no red badge updating with correct value) as it was not originally built with aliases stuff supported/tested.

**Comment by joshirio** [comment]
I'm sorry, this was an user error 😳
now it works as intended (there was a custom filter which marked the mail as read on my dad's mac)
