### ISSUE TITLE
Feature request: change order of email tabs

### ISSUE THREAD

**Issue by jeroen7s** [vladimiry/email-securely-app#40]
pretty much the title
being able to put the different mail-addresses in a specific order would be nice
right now the only way to do this is to remove your email-accounts and re-add them in the correct order

**Comment by vladimiry** [comment]
This is how it's going to look:

![reorder](https://user-images.githubusercontent.com/1560781/43458732-f97334a2-94d3-11e8-96b6-c3cb98c6ad11.gif)

**Comment by vladimiry** [comment]
Released with [v1.4.0](https://github.com/vladimiry/email-securely-app/releases/tag/v1.4.0).

**Comment by jeroen7s** [comment]
That was fast
Thanks a lot! :)
