### ISSUE TITLE
temporary node file with random name - issue 5 regression

### ISSUE THREAD

**Issue by ask2018** [vladimiry/email-securely-app#41]
Since version 1.2.0 there is back this problem - https://github.com/vladimiry/email-securely-app/issues/5
Up to version 1.1.1 everything is ok.

**Comment by vladimiry** [comment]
The solution for https://github.com/vladimiry/email-securely-app/issues/5 was in unpacking native dependencies, so Electron doesn't unpack them every time with a random file name. It might be that new native dependencies got added which I didn't care to unpack yet, will look into it.

Meanwhile, it would be helpful to get more details. Like OS name and version used, temporary files location, exact files size in bytes or md5 hash of those files (so I could know for sure which native dependency it's related to).

**Comment by ask2018** [comment]
OS is the same as for issue 5 - Win 7 64bit with all security updates
Versions from 1.2.0 to 1.4.0 
temporary files location - same as for issue 5 - "C:\Users\USERNAME\AppData\Local\Temp\some_random_string.tmp.node"
File size for version 1.4.0 - some_random_string.tmp.node - 522752 bytes
MD5 for version 1.4.0 - some_random_string.tmp.node - a68852ad89aa2b1f7c2c7b3e0b402fbc

**Comment by vladimiry** [comment]
That file is a `leveldown` related native dependency, add as a part of the local store WIP feature.

Here is the version with fix applyed - [email-securely-app-1.4.1-windows-nsis-installer.exe](https://www.dropbox.com/s/gxp7p7o7rlvgv85/email-securely-app-1.4.1-windows-nsis-installer.exe?dl=1), will be included into the next release. Please confirm it solves the issue.

**Comment by ask2018** [comment]
Unfortunately still the same problem with version 1.4.1 you posted. File size and MD5 are also still the same for node file.

**Comment by vladimiry** [comment]
Did some changes and made sure that [this](https://www.dropbox.com/s/w9s7daxlwyms880/email-securely-app-1.4.1-windows-nsis-installer.exe?dl=1) version doesn't create 522752 bytes sized temp file anymore (`leveldown` binary), running Win 10.

I noticed though that app creates a png icon file with a randomly generated name in the same temp folder, let me know if that's a deal breaker.

**Comment by ask2018** [comment]
Now it works fine. Thank you. PNG file I've also noticed before, but that should not be problem for me.

**Comment by vladimiry** [comment]
Ok, closing then as resolved.
