### ISSUE TITLE
Feature request, use of a $BROWSER variable or add option to set default browser

### ISSUE THREAD

**Issue by freed00m** [vladimiry/email-securely-app#45]
I know chromium on linux uses `xdg-open`, but I dislike xdg as I don't know how to configure it or how to set a default browser. I think maybe many other users could be left puzzled why their links are being openned in firefox instead of they default browser.

Maybe if $BROWSER would exist, use that one instead?

Just an idea mainly for linux users.

**Comment by vladimiry** [comment]
Hi @freed00m, I'd prefer to avoid adding OS specific logic into the app, at least if that's not really necessary. So I have to decline this feature request.

You can set the default browser calling similar command `xdg-settings set default-web-browser firefox.desktop`, see respective Arch Wiki [page](https://wiki.archlinux.org/index.php/Xdg-utils). You can find all the desktop shortcuts in the /usr/share/applications folder.

**Comment by freed00m** [comment]
@vladimiry that is not working couse the xdg-settings wont set browser if the $BROWSER variable exists and set.
Despite being set, xdg ignores it.

```
$ xdg-settings set default-web-browser chromium.desktop
xdg-settings: $BROWSER is set and can't be changed with xdg-settings
$ echo $BROWSER
qutebrowser
``` 
and links are being openned in firefox.. That's why I hate xdg, I wanted to have $BROWSER honored.

Agreed this issue is upstream and can stay as WONTFIX.

**Comment by dirkjanvanvliet** [comment]
I hope I am allowed to ask my question here, many thanks in advance. But I have the problem in Kubuntu 20.04 that all links in ElectronMail are opened in Firefox and not in my default browser. 

In the OS I've set Vivaldi as my default browser and also I run the following command in the terminal (which did not give any errors):
`xdg-settings set default-web-browser chromium.desktop`

It's a minor issue, though would be nice if this can be fixed either in ElectronMail or on my user-side. 
![electronmail](https://user-images.githubusercontent.com/21241932/86910808-88674080-c11a-11ea-8e1c-0dd2f3ac9d22.png)

**Comment by vladimiry** [comment]
I don't have installed Kubuntu to test the case. Maybe try some steps listed in https://askubuntu.com/questions/788043/where-to-change-how-xdg-open-opens-urls-sync-with-kde-open.

**Comment by dirkjanvanvliet** [comment]
> I don't have installed Kubuntu to test the case. Maybe try some steps listed in https://askubuntu.com/questions/788043/where-to-change-how-xdg-open-opens-urls-sync-with-kde-open.

Many thanks, this fixed it. I've run these commands in the terminal:

`$ xdg-settings set default-url-scheme-handler http vivaldi.desktop
$ xdg-settings set default-url-scheme-handler https vivaldi.desktop`

That fixed it. Many thanks again and also for the development of this app!
