### ISSUE TITLE
Allow https://beta.protonmail.com/inbox

### ISSUE THREAD

**Issue by LM1LC3N7** [vladimiry/email-securely-app#46]
Hello,

Can you allow the new protonmail beta URL ?

https://beta.protonmail.com/inbox

Thanks!

**Comment by vladimiry** [comment]
Sure. Going to publish a new version later today.

**Comment by vladimiry** [comment]
You got it with just published v1.5.0 version, see [releases](https://github.com/vladimiry/email-securely-app/releases) page.
