### ISSUE TITLE
App starts minimized to tray even when when option is diabled

### ISSUE THREAD

**Issue by joshirio** [vladimiry/email-securely-app#47]
This issue affects Windows, Linux (tested on Ubuntu, Manjaro KDE) but not macOS.

Settings:
![2018-09-20_09-05-46](https://user-images.githubusercontent.com/12795018/45801548-72259180-bcb4-11e8-802a-7b3215ea8d52.png)

Example:
![2018-09-20_09-04-16](https://user-images.githubusercontent.com/12795018/45801558-79e53600-bcb4-11e8-92f0-18326ce1a28f.gif)

**Comment by vladimiry** [comment]
Thanks for testing on all the platforms! I confirm the bug. Looks like it takes place only in case of a [maximized window](https://github.com/vladimiry/email-securely-app/blob/068975c926c2ef85e600c30e4ad4566c82f52197/src/electron-main/window.ts#L91).

**Comment by vladimiry** [comment]
Fix has landed into the master branch, will be included in the next release.

**Comment by vladimiry** [comment]
@joshirio can you confirm that just released [v1.5.1](https://github.com/vladimiry/email-securely-app/releases/tag/v1.5.1) has no such issue?

**Comment by joshirio** [comment]
Yes works well, thank you.
