### ISSUE TITLE
Disable portable builds for Windows

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/email-securely-app#60]
Desktop notifications feature doesn't work with portable packages. So it makes sense to stop shipping packages of such kind in order to avoid issues like [this](https://github.com/vladimiry/email-securely-app/issues/58) happening.

**Comment by seascape** [comment]
Ah, unfortunate. I was just typing up a suggestion for a portable Windows build. That's a major value-adder for me. Sounds like there are technical drawbacks though.

**Comment by vladimiry** [comment]
@seascape unfortunately notifications feature doesn't work with portable packages by design  (Windows 10 restriction), so I had to disable portable builds to avoid possible confusions. Anyway that was not a real portable build since app's settings folder was still the same as used with regular packages, ie located somewhere in the user's directory but not inside the portable folder close to the app.
