### ISSUE TITLE
After clicking the Close button on a Mac, the window will not re-open by clicking the icon in the dock

### ISSUE THREAD

**Issue by ohkeepa** [vladimiry/email-securely-app#63]
After clicking the Close button on a Mac, the window will not re-open by clicking the icon in the dock.  It also cannot be made visible by right-clicking the icon in the dock and choosing "Show All Windows".   However, it can be made visible again by clicking the icon in the menu bar and choosing "Toggle Window".

Application version: 1.5.2
OS Version: macOS Mojave 10.14

**Comment by vladimiry** [comment]
Can you confirm that version shared [here](https://github.com/vladimiry/email-securely-app/issues/50#issuecomment-432005162) has no described issues?

**Comment by ohkeepa** [comment]
Yes, that version solves the problem, thanks!

**Comment by vladimiry** [comment]
Fix is going to be published soon with a new release.
