### ISSUE TITLE
Support ProtonMail's src/app/commons/models/label.js change

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/email-securely-app#69]
Protonmail changed the [labels data model](https://github.com/ProtonMail/WebClient/commits/public/src/app/commons/models/label.js) 3 days ago with this [commit](https://github.com/ProtonMail/WebClient/commit/f9d764a13a684e2f43e386132d8e61a2349f72be#diff-8433f1f071133ab43181db1b2b08aa51R9).

This is a breaking change which ends up with the `Cannot read property 'Labels' of undefined` error at the app side. The fix is going to be simple.

For the future, I better consider calling the Rest API directly rather than relying on Protonmail WebClient, as normally WebClient code changing happens quite more often than API changing and since this is an unofficial app there is no synchronization in WebClient and this app development.

**Comment by vladimiry** [comment]
@vensko can you a the new [2.0.0-beta.6](https://www.dropbox.com/s/9b3vxqtw1if100g/email-securely-app-2.0.0-beta.6-windows-nsis-installer.exe?dl=1) build and confirm that the local store and app built-in export features got back to work for you, ie no `Cannot read property 'Labels' of undefined` error anymore?

**Comment by vladimiry** [comment]
Fixed with [2.0.0-beta.6](https://github.com/vladimiry/email-securely-app/releases/tag/2.0.0-beta.6) release.

**Comment by vensko** [comment]
Exception on start:
![securely6](https://user-images.githubusercontent.com/1040510/48651067-71318780-e9f9-11e8-8476-d59c806d2495.png)

**Comment by vensko** [comment]
During "Data loading", got the exception:
```
[2018-11-17 00:14:46.172] [error] [src/electron-main/database/entity-map] [ ValidationError {
    value: [],
    property: 'toRecipients',
    children: [],
    constraints: { mailRecipientsSize: 'Invalid recipients list' } } ]
[2018-11-17 00:14:46.175] [error] emitted.error: {"index":0} Error: toRecipients: {"mailRecipientsSize":"Invalid recipients list"}
    at Function.generateValidationError (C:\Users\Dima\AppData\Local\Programs\email-securely-app\resources\app.asar\app\electron-main.js:1:55681)
    at d.<anonymous> (C:\Users\Dima\AppData\Local\Programs\email-securely-app\resources\app.asar\app\electron-main.js:1:56197)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Dima\AppData\Local\Programs\email-securely-app\resources\app.asar\node_modules\tslib\tslib.js:105:69)

[2018-11-17 00:14:46.181] [error] [WEB] [reducers/errors] <[account.component][0]> { message:
   'toRecipients: {"mailRecipientsSize":"Invalid recipients list"}',
  name: 'Error' }
```
Can't tell, which letter caused this.

**Comment by vensko** [comment]
Export worked ok, and as for garbled output, it was EML viewer plugin for Total Commander, which apparently does not fully support the format. Thunderbird indeed shows them correctly.

**Comment by vladimiry** [comment]
> Exception on start while checking for update (UPD: I rolled back to b5 and still getting it, something in configuration?):

This is a good catch. I accidentally named the release as `2.0.0-beta.6` missing the required `v` prefix. Just created the proper `v2.0.0-beta.6` tag, the app should start without errors now.
