### ISSUE TITLE
Database persistance ValidationError with "Invalid recipients list" messasge

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/email-securely-app#70]
This is a follow up to the issue revealed by @vensko here https://github.com/vladimiry/email-securely-app/issues/69#issuecomment-439557822

@vensko, you somehow got emails with empty recipients list. There is a custom database persistance validation enabled that accepts empty recipients list only in case of email is in `draft` state. I assumed that this is an invalid case to have empty recipients for arbitrary email state, so going to disable the [respective validation](https://github.com/vladimiry/email-securely-app/blob/9491f459ccc9758b576b932bb293acacec52cc99/src/electron-main/database/entity/validation/mail-recipients-size.ts).

**Comment by vladimiry** [comment]
@vensko can you try the beta 7 build uploaded [here](https://www.dropbox.com/sh/rrg0pj8x4jb6hwr/AABrk2yVgs7_EjJ1Dyd5lzACa?dl=0)? There should be no `Invalid recipients list` validation error anymore.

**Comment by vensko** [comment]
Yes, the error is gone.
