### ISSUE TITLE
Tray icon issue on linux KDE

### ISSUE THREAD

**Issue by Heziode** [vladimiry/email-securely-app#75]
The icon are bad rendered in the system tray on linux with KDE DE.

I have tested the solution provided by @joshirio, `XDG_CURRENT_DESKTOP=Unity "/opt/email-securely-app/email-securely-app" %U` it it doesn't change anything.

The icon is just near the system stats at the top right of the screen. The first screenshot show the tray icon without new mail, the second is the tray icon when I have unread mails.

![tray icon without new mail](https://user-images.githubusercontent.com/16735076/48962627-5a071280-ef82-11e8-9741-c693c00bb33f.png)

![tray icon with new mail](https://user-images.githubusercontent.com/16735076/48962628-5a071280-ef82-11e8-83db-9ab2be657bc7.png)

ESA version: v2.0.0-beta.7

I have the same issue with [Riot](https://github.com/vector-im/riot-web/).

*Nb: I use [HiDPI](https://wiki.archlinux.org/index.php/HiDPI) with a scale of 2, so It show 1920x1080 on 3840x2160.*

**Comment by Heziode** [comment]
It seems to work when I remove `libappindicator`. This is a dependance of this project on Archlinux (and maybe other linux package distro).

![tray_icon_without_libappindicator](https://user-images.githubusercontent.com/16735076/48962986-8b371100-ef89-11e8-908c-251b5c785c41.png)


Remove on archlinux: `pacman -Rdd libappindicator-gtk3 libappindicator-sharp libappindicator-gtk2`

**Comment by vladimiry** [comment]
Thanks for figuring it out. So now other users with similar to your setup, KDE + HiDPI, will know what they need to do.

**Comment by Heziode** [comment]
Yep,

And I don't think is related to HiDPI but only with libappindicator.

**Comment by vladimiry** [comment]
But the way in your case icon looks very blurred, similar to how it looks on macOS. But it looks very sharp in case of Xfce use, so I recommend using Xfce :smile:
