### ISSUE TITLE
Error decrypting message: Session key decryption failed

### ISSUE THREAD

**Issue by joshirio** [vladimiry/email-securely-app#85]
![email-securely-app_2018-12-25_12-47-43](https://user-images.githubusercontent.com/12795018/50423890-f5c6bf80-085b-11e9-91c4-a0c23eb301c3.png)

After the update to v2.0.0 one of three protonmail accounts show this error message when I enable the local storage feature.

I already tried to delete and re-add the account without success. Tested on macOS and Windows with same result.

**Comment by vladimiry** [comment]
- Is there somehing in app log file (app settings folder)?
- I have a guess that there will be the same error if opening email in Google Chrome browser. Is there a way you could open for view all the emails of that problematic account using Google Chrome browser (version close to 69.0.3497.106 if possible)? I uderstant this is not a case if you got a lot of emails there, but that would help to narrow down the scope.

From first glance this looks like `openpgp.decryptSessionKeys` call error (function source is [here](https://github.com/openpgpjs/openpgpjs/blob/1bee091f2acd054b9cd78c6eca5c139061761662/src/message.js#L153)). It's the Protonmail's internals, being triggered by the app on calling [messageModel.clearTextBody](https://github.com/vladimiry/email-securely-app/blob/4d66a743f92cda77ab38b1415811ef0b851b31fd/src/electron-preload/webview/protonmail/lib/database/mail.ts#L36) function during preparing a message for storing in database. The Protonmail's call goes from [here](https://github.com/ProtonMail/WebClient/blob/public/src/app/message/factories/messageModel.js#L523) and deeper through `AttachmentLoader.reverify` call down to openpgp's `openpgp.decryptSessionKeys` call.

**Comment by vladimiry** [comment]
> do you mean there must be one particular email in my archive causing this error which could be deleted and then the problem is gone?

Correct.

The error is cause is at the protonmail's side. When you enable the local store, the app does the bootstrap fetch first (fetches all the messages, folders and contacts). During this fetch the app calls protonmail's [clearTextBody](https://github.com/ProtonMail/WebClient/blob/public/src/app/message/factories/messageModel.js#L523) function and this is where the error occurs.

**Comment by vladimiry** [comment]
> webclient0://app.protonmail.ch/openpgp.min.15c1c0e67bc62a0edb4f35d931f0f17e7722f9ec.js:2:486997

Thanks for the log, so yes initial guess was correct.

**Comment by joshirio** [comment]
OK this is interesting, I opened all my emails in each folder one by one, no error occurred. Then I deleted all my spam emails and emptied the trash. Now I readded the account and enabled the feature and **it works**. So maybe I was lucky to delete the problematic email by chance.

I will add the account to my second desktop pc to see if this issue is solved for good or if I was just lucky after trying to add/delete the account after several trials.

Thanks.

**Comment by vladimiry** [comment]
If that occurs again I think I will noticed that, and then there will be a need to:
- Identify the problematic email.
- Call [clearTextBody](https://github.com/ProtonMail/WebClient/blob/public/src/app/message/factories/messageModel.js#L523) for that problematic email, same as the app does [here](https://github.com/vladimiry/email-securely-app/blob/4d66a743f92cda77ab38b1415811ef0b851b31fd/src/electron-preload/webview/protonmail/lib/database/mail.ts#L36).
- Raise a bug [here](https://github.com/ProtonMail/WebClient) if error occurs on problematic email with running in regular browser

**Comment by joshirio** [comment]
I think this is fine, since the subject line is not encrypted anyway and also because the log file is kept locally so it should not be a big issue. And it's not like every subject of all the emails is logged all the time.

+1

**Comment by vladimiry** [comment]
Reopening until this is done:

> print the email's subject to log file if body forming fails

**Comment by jeroen7s** [comment]
i'm still having this issue in 1 of my accounts, how do I fix this? :/

**Comment by vladimiry** [comment]
@jeroen7s [this](https://www.dropbox.com/sh/7sbderca1bqhjgd/AAAm8tMMUdy8PW_6W49Bizrna?dl=0&lst=) build enables printing problematic email's subject to a log file in along with the error. Ideally, you open that email in Google Chrome browser (version close to 69.0.3497.106 if possible). Generally removing problematic email should fix the issue.
