### ISSUE TITLE
user agent

### ISSUE THREAD

**Issue by MalevolentGrin** [vladimiry/email-securely-app#88]
What User Agent is provided to TN?

**Comment by vladimiry** [comment]
These are user agents I've taken from CI servers,  basically same Chromium version that used Electron version [comes with](https://github.com/electron/electron/releases/tag/v4.0.0):
- linux
 ![ua-linux](https://user-images.githubusercontent.com/1560781/50524031-7e579100-0ae4-11e9-84c9-58dbc15a30da.png)
- osx
  ![ua-osx](https://user-images.githubusercontent.com/1560781/50524041-86173580-0ae4-11e9-8de1-3c6d96f333de.png)
- win
  ![ua-win](https://user-images.githubusercontent.com/1560781/50524048-8adbe980-0ae4-11e9-8125-2c014cc824f7.png)

By default user agent of the Electron based app also includes app name and "electron" keyword. I [purified](https://github.com/vladimiry/email-securely-app/commit/163d246355ef284dbd9ea01773654ffac99f7afc#diff-b646faac5392db03f6bfb67005ef0582R42) this app's user agent about a month ago and so it doesn't include such data anymore. So it's now prrety similar to a regular browser, but still if Protonmail/Tutanota will need to target users of this app, I belive they will be able to find a way.

Let me know if provided information resolves the issue.

**Comment by vladimiry** [comment]
Closing as resolved.
