### ISSUE TITLE
Select all context menu action is missing ("ctrl+a" hokey)

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/email-securely-app#90]

**Comment by vladimiry** [comment]
> - CMD-A (for selecting "all") too for editing in forms (search etc.) and especially when deleting whole email ...

@tombarys can you try [this](https://www.dropbox.com/sh/7sbderca1bqhjgd/AAAm8tMMUdy8PW_6W49Bizrna?dl=0&lst=) build? It's the same build as shared here https://github.com/vladimiry/email-securely-app/issues/87#issuecomment-450550478.

**Comment by tombarys** [comment]
Vladimir, as for now, both Cmd-A and Cmd-F work :) Great!

The problem I have is when logging in using two factor auth – the code always changes but the workflow tries to use the saved one (in settings), so it renders in error and neccessity to log manually.

Thanks!

–––––––––––––
Tomáš Baránek
http://barys.me
tom@barys.me

🔐 TIP: nechcete-li, aby poskytovatel mailu či někdo jiný mohl zneužít obsah vašich zpráv, zkuste skvělý švýcarský šifrovaný [ProtonMail.com](http://www.protonmail.com/).

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
neděle 30. prosinec 2018 11:05, Vladimir Yakovlev <notifications@github.com> napsal:

**Comment by vladimiry** [comment]
> The problem I have is when logging in using two factor auth – the code always changes but the workflow tries to use the saved one (in settings), so it renders in error and neccessity to log manually. 

If you need automatic 2FA token filling, you need to enter 2FA secret seed (so app is able to generate tokens independenty), not the 2FA token. See details here https://github.com/vladimiry/email-securely-app/issues/10.

**Comment by vladimiry** [comment]
Closing as resolved. The feature will be a part of the next release.
