### ISSUE TITLE
Disable red notification.

### ISSUE THREAD

**Issue by lukapercic** [vladimiry/email-securely-app#91]
![image](https://user-images.githubusercontent.com/4706356/50695166-31237400-103c-11e9-9acb-117bb812d49f.png)
Allow disabling of the red colour for unread notification (preferably, only show how many emails are new since the last time you looked). Red is designed to mess with people heads (mark all as read till it vanishes). Many people (like me) don't want to read most of their emails and would like to leave them unread without the red colour or being triggered every time.

Same goes for the icon in the taskbar;
![image](https://user-images.githubusercontent.com/4706356/50695371-b7d85100-103c-11e9-8af2-f6f81991b755.png)

**Comment by vladimiry** [comment]
Going to look into this after handling more critical issues.

@lukapercic would adding a background colour selection option resolve the issue? Like we have red and grey background colours in the list to select from, and maybe even custom colour?

**Comment by lukapercic** [comment]
I don't really understand what the background colour would actually colour... the background of the tab?

From my perspective, you either allow people to disable the unread red notification, or you make it grey (un-interesting for eyes to lock on). Red needs to go.

**Comment by vladimiry** [comment]
> I don't really understand what the background colour would actually colour... the background of the tab?

> or you make it grey

This. I'm considering enabling an option to change red colour from red to grey.

**Comment by lukapercic** [comment]
That would solve it, yes. It does need to be changeable on the icon as well.

**Comment by vladimiry** [comment]
> It does need to be changeable on the icon as well.

Sure. I did care already rendering the tray icon colour not using a static image but programmatically, so that should be easy to support colours customization.

**Comment by vladimiry** [comment]
@lukapercic, I didn't know what color you like the most and so I enabled custom color selection, hope this works.

  ![unread-badge-2-2](https://user-images.githubusercontent.com/1560781/51189778-c7378400-18f1-11e9-925c-e5b3727efdf4.gif)

A new release is on the way :shipit:

**Comment by vladimiry** [comment]
Resolved with [v2.2.0](https://github.com/vladimiry/email-securely-app/releases/tag/v2.2.0) release.

**Comment by vladimiry** [comment]
Next release will include text color customization.

![unread-badge-customization](https://user-images.githubusercontent.com/1560781/51834103-5be6ac80-230a-11e9-9a9d-edbf3574a3c8.gif)
