### ISSUE TITLE
Select the next email when one is deleted, and with arrow-keys in ProtonMail?

### ISSUE THREAD

**Issue by ohkeepa** [vladimiry/email-securely-app#95]
Currently in ProtonMail, if you hit the DEL key on the keyboard to delete a message, the next message is not selected and displayed.  Instead, a "Welcome" message appears where an email would appear. 

I contacted ProtonMail support, and they said that is how it is supposed to work, and that they would pass along my suggestion to the development team.

In addition, if an email is selected, the up and down arrow keys to not change focus to previous and next emails because the reading pane appears to get focus.  This makes it difficult to use only the keyboard to navigate and read emails.

Would it be possible to implement these behaviors within the email-securely-app instead?

**Comment by vladimiry** [comment]
I believe that would be possible to achieve doing monkey patching of the official web client. The proper way though is handing it here https://github.com/ProtonMail/WebClient but as you wrote ProtonMail has rejected the issue.

Monkey patching is, in general, an unreliable approach required thoroughly testing the patching logic with every web client update. So for sake of app stability, it's better to avoid expanding monkey patching hacks use in the app (there are some hacks already in the app).

So closing the issue as outside of the desktop app scope.
